-- OPPRETT TABELLER FOR COFOUND

-- 1. PROFILER (Utvidet brukerinfo som kobles til Supabase Auth)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  role text,
  avatar text,
  bio text,
  skills text[],
  experience jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Skru på sikkerhet (RLS)
alter table public.profiles enable row level security;

-- Regler for hvem som kan se og endre profiler
create policy "Alle kan se profiler" on public.profiles
  for select using (true);

create policy "Brukere kan endre sin egen profil" on public.profiles
  for update using (auth.uid() = id);

create policy "Brukere kan slette sin egen profil" on public.profiles
  for delete using (auth.uid() = id);

create policy "Brukere kan opprette sin egen profil" on public.profiles
  for insert with check (auth.uid() = id);


-- 2. INNLEGG (Posts)
create table public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  title text not null,
  description text not null,
  category text not null,
  tags text[],
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Skru på sikkerhet (RLS)
alter table public.posts enable row level security;

-- Regler for innlegg
create policy "Alle kan se innlegg" on public.posts
  for select using (true);

create policy "Innloggede brukere kan opprette innlegg" on public.posts
  for insert with check (auth.role() = 'authenticated');

create policy "Brukere kan endre egne innlegg" on public.posts
  for update using (auth.uid() = user_id);

create policy "Brukere kan slette egne innlegg" on public.posts
  for delete using (auth.uid() = user_id);


-- 3. MELDINGER
create table public.messages (
  id bigint generated by default as identity primary key,
  from_id uuid references public.profiles(id) not null,
  to_id uuid references public.profiles(id) not null,
  subject text,
  content text not null,
  is_read boolean default false,
  post_title text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Skru på sikkerhet (RLS)
alter table public.messages enable row level security;

-- Regler for meldinger (VIKTIG FOR SIKKERHET)
create policy "Brukere kan se meldinger de har sendt eller mottatt" on public.messages
  for select using (auth.uid() = from_id or auth.uid() = to_id);

create policy "Innloggede brukere kan sende meldinger" on public.messages
  for insert with check (auth.role() = 'authenticated');

create policy "Mottakere kan markere meldinger som lest" on public.messages
  for update using (auth.uid() = to_id);


-- 4. LOGIC FOR Å AUTOMATISK OPPRETTE PROFIL VED SIGNUP (Avansert, men nyttig)
-- Dette gjør at når en bruker registrerer seg, opprettes en profil automatisk
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name, avatar, role)
  values (new.id, new.email, new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'avatar', new.raw_user_meta_data->>'role');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 5. FAVORITTER
create table public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  item_id text not null, -- ID til innlegg eller bruker (kan være uuid eller tall, så text er tryggest)
  type text not null, -- 'project' eller 'user'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, item_id, type)
);

alter table public.favorites enable row level security;

create policy "Brukere kan se sine egne favoritter" on public.favorites
  for select using (auth.uid() = user_id);

create policy "Brukere kan legge til favoritter" on public.favorites
  for insert with check (auth.uid() = user_id);

create policy "Brukere kan slette sine egne favoritter" on public.favorites
  for delete using (auth.uid() = user_id);
